
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.ts'
export { Prisma }
export * as $Enums from './enums.ts'
export * from './enums.ts';
/**
 * Model file_groups
 * 
 */
export type file_groups = Prisma.file_groupsModel
/**
 * Model file_index
 * 
 */
export type file_index = Prisma.file_indexModel
/**
 * Model migrations
 * 
 */
export type migrations = Prisma.migrationsModel
/**
 * Model session_tokens
 * 
 */
export type session_tokens = Prisma.session_tokensModel
/**
 * Model users
 * 
 */
export type users = Prisma.usersModel
