
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.ts'
export type * from './prismaNamespace.ts'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  file_groups: 'file_groups',
  file_index: 'file_index',
  migrations: 'migrations',
  session_tokens: 'session_tokens',
  users: 'users'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const File_groupsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  file_ids: 'file_ids',
  user_id: 'user_id',
  created_at: 'created_at'
} as const

export type File_groupsScalarFieldEnum = (typeof File_groupsScalarFieldEnum)[keyof typeof File_groupsScalarFieldEnum]


export const File_indexScalarFieldEnum = {
  id: 'id',
  visibility: 'visibility',
  date_added: 'date_added',
  file_size_in_bytes: 'file_size_in_bytes',
  stored_filename: 'stored_filename',
  original_name: 'original_name',
  mime_type: 'mime_type',
  user_id: 'user_id'
} as const

export type File_indexScalarFieldEnum = (typeof File_indexScalarFieldEnum)[keyof typeof File_indexScalarFieldEnum]


export const MigrationsScalarFieldEnum = {
  id: 'id',
  filename: 'filename',
  applied_at: 'applied_at'
} as const

export type MigrationsScalarFieldEnum = (typeof MigrationsScalarFieldEnum)[keyof typeof MigrationsScalarFieldEnum]


export const Session_tokensScalarFieldEnum = {
  token: 'token',
  user_id: 'user_id',
  is_valid: 'is_valid',
  user_agent: 'user_agent',
  added_on: 'added_on'
} as const

export type Session_tokensScalarFieldEnum = (typeof Session_tokensScalarFieldEnum)[keyof typeof Session_tokensScalarFieldEnum]


export const UsersScalarFieldEnum = {
  id: 'id',
  username: 'username',
  password_hash: 'password_hash',
  quota_in_bytes: 'quota_in_bytes',
  is_admin: 'is_admin',
  date_of_creation: 'date_of_creation'
} as const

export type UsersScalarFieldEnum = (typeof UsersScalarFieldEnum)[keyof typeof UsersScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const file_groupsOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  file_ids: 'file_ids',
  user_id: 'user_id'
} as const

export type file_groupsOrderByRelevanceFieldEnum = (typeof file_groupsOrderByRelevanceFieldEnum)[keyof typeof file_groupsOrderByRelevanceFieldEnum]


export const file_indexOrderByRelevanceFieldEnum = {
  id: 'id',
  stored_filename: 'stored_filename',
  original_name: 'original_name',
  mime_type: 'mime_type',
  user_id: 'user_id'
} as const

export type file_indexOrderByRelevanceFieldEnum = (typeof file_indexOrderByRelevanceFieldEnum)[keyof typeof file_indexOrderByRelevanceFieldEnum]


export const migrationsOrderByRelevanceFieldEnum = {
  id: 'id',
  filename: 'filename'
} as const

export type migrationsOrderByRelevanceFieldEnum = (typeof migrationsOrderByRelevanceFieldEnum)[keyof typeof migrationsOrderByRelevanceFieldEnum]


export const session_tokensOrderByRelevanceFieldEnum = {
  token: 'token',
  user_id: 'user_id',
  user_agent: 'user_agent'
} as const

export type session_tokensOrderByRelevanceFieldEnum = (typeof session_tokensOrderByRelevanceFieldEnum)[keyof typeof session_tokensOrderByRelevanceFieldEnum]


export const usersOrderByRelevanceFieldEnum = {
  id: 'id',
  username: 'username',
  password_hash: 'password_hash'
} as const

export type usersOrderByRelevanceFieldEnum = (typeof usersOrderByRelevanceFieldEnum)[keyof typeof usersOrderByRelevanceFieldEnum]

