
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `file_groups` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model file_groups
 * 
 */
export type file_groupsModel = runtime.Types.Result.DefaultSelection<Prisma.$file_groupsPayload>

export type AggregateFile_groups = {
  _count: File_groupsCountAggregateOutputType | null
  _min: File_groupsMinAggregateOutputType | null
  _max: File_groupsMaxAggregateOutputType | null
}

export type File_groupsMinAggregateOutputType = {
  id: string | null
  name: string | null
  file_ids: string | null
  user_id: string | null
  created_at: Date | null
}

export type File_groupsMaxAggregateOutputType = {
  id: string | null
  name: string | null
  file_ids: string | null
  user_id: string | null
  created_at: Date | null
}

export type File_groupsCountAggregateOutputType = {
  id: number
  name: number
  file_ids: number
  user_id: number
  created_at: number
  _all: number
}


export type File_groupsMinAggregateInputType = {
  id?: true
  name?: true
  file_ids?: true
  user_id?: true
  created_at?: true
}

export type File_groupsMaxAggregateInputType = {
  id?: true
  name?: true
  file_ids?: true
  user_id?: true
  created_at?: true
}

export type File_groupsCountAggregateInputType = {
  id?: true
  name?: true
  file_ids?: true
  user_id?: true
  created_at?: true
  _all?: true
}

export type File_groupsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which file_groups to aggregate.
   */
  where?: Prisma.file_groupsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of file_groups to fetch.
   */
  orderBy?: Prisma.file_groupsOrderByWithRelationInput | Prisma.file_groupsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.file_groupsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` file_groups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` file_groups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned file_groups
  **/
  _count?: true | File_groupsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: File_groupsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: File_groupsMaxAggregateInputType
}

export type GetFile_groupsAggregateType<T extends File_groupsAggregateArgs> = {
      [P in keyof T & keyof AggregateFile_groups]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFile_groups[P]>
    : Prisma.GetScalarType<T[P], AggregateFile_groups[P]>
}




export type file_groupsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.file_groupsWhereInput
  orderBy?: Prisma.file_groupsOrderByWithAggregationInput | Prisma.file_groupsOrderByWithAggregationInput[]
  by: Prisma.File_groupsScalarFieldEnum[] | Prisma.File_groupsScalarFieldEnum
  having?: Prisma.file_groupsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: File_groupsCountAggregateInputType | true
  _min?: File_groupsMinAggregateInputType
  _max?: File_groupsMaxAggregateInputType
}

export type File_groupsGroupByOutputType = {
  id: string
  name: string
  file_ids: string
  user_id: string
  created_at: Date | null
  _count: File_groupsCountAggregateOutputType | null
  _min: File_groupsMinAggregateOutputType | null
  _max: File_groupsMaxAggregateOutputType | null
}

type GetFile_groupsGroupByPayload<T extends file_groupsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<File_groupsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof File_groupsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], File_groupsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], File_groupsGroupByOutputType[P]>
      }
    >
  >



export type file_groupsWhereInput = {
  AND?: Prisma.file_groupsWhereInput | Prisma.file_groupsWhereInput[]
  OR?: Prisma.file_groupsWhereInput[]
  NOT?: Prisma.file_groupsWhereInput | Prisma.file_groupsWhereInput[]
  id?: Prisma.StringFilter<"file_groups"> | string
  name?: Prisma.StringFilter<"file_groups"> | string
  file_ids?: Prisma.StringFilter<"file_groups"> | string
  user_id?: Prisma.StringFilter<"file_groups"> | string
  created_at?: Prisma.DateTimeNullableFilter<"file_groups"> | Date | string | null
  users?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.usersWhereInput>
}

export type file_groupsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  file_ids?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  users?: Prisma.usersOrderByWithRelationInput
  _relevance?: Prisma.file_groupsOrderByRelevanceInput
}

export type file_groupsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.file_groupsWhereInput | Prisma.file_groupsWhereInput[]
  OR?: Prisma.file_groupsWhereInput[]
  NOT?: Prisma.file_groupsWhereInput | Prisma.file_groupsWhereInput[]
  name?: Prisma.StringFilter<"file_groups"> | string
  file_ids?: Prisma.StringFilter<"file_groups"> | string
  user_id?: Prisma.StringFilter<"file_groups"> | string
  created_at?: Prisma.DateTimeNullableFilter<"file_groups"> | Date | string | null
  users?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.usersWhereInput>
}, "id">

export type file_groupsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  file_ids?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.file_groupsCountOrderByAggregateInput
  _max?: Prisma.file_groupsMaxOrderByAggregateInput
  _min?: Prisma.file_groupsMinOrderByAggregateInput
}

export type file_groupsScalarWhereWithAggregatesInput = {
  AND?: Prisma.file_groupsScalarWhereWithAggregatesInput | Prisma.file_groupsScalarWhereWithAggregatesInput[]
  OR?: Prisma.file_groupsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.file_groupsScalarWhereWithAggregatesInput | Prisma.file_groupsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"file_groups"> | string
  name?: Prisma.StringWithAggregatesFilter<"file_groups"> | string
  file_ids?: Prisma.StringWithAggregatesFilter<"file_groups"> | string
  user_id?: Prisma.StringWithAggregatesFilter<"file_groups"> | string
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"file_groups"> | Date | string | null
}

export type file_groupsCreateInput = {
  id: string
  name: string
  file_ids: string
  created_at?: Date | string | null
  users: Prisma.usersCreateNestedOneWithoutFile_groupsInput
}

export type file_groupsUncheckedCreateInput = {
  id: string
  name: string
  file_ids: string
  user_id: string
  created_at?: Date | string | null
}

export type file_groupsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  file_ids?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  users?: Prisma.usersUpdateOneRequiredWithoutFile_groupsNestedInput
}

export type file_groupsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  file_ids?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type file_groupsCreateManyInput = {
  id: string
  name: string
  file_ids: string
  user_id: string
  created_at?: Date | string | null
}

export type file_groupsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  file_ids?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type file_groupsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  file_ids?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type file_groupsOrderByRelevanceInput = {
  fields: Prisma.file_groupsOrderByRelevanceFieldEnum | Prisma.file_groupsOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type file_groupsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  file_ids?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type file_groupsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  file_ids?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type file_groupsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  file_ids?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type File_groupsListRelationFilter = {
  every?: Prisma.file_groupsWhereInput
  some?: Prisma.file_groupsWhereInput
  none?: Prisma.file_groupsWhereInput
}

export type file_groupsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type file_groupsCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.file_groupsCreateWithoutUsersInput, Prisma.file_groupsUncheckedCreateWithoutUsersInput> | Prisma.file_groupsCreateWithoutUsersInput[] | Prisma.file_groupsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.file_groupsCreateOrConnectWithoutUsersInput | Prisma.file_groupsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.file_groupsCreateManyUsersInputEnvelope
  connect?: Prisma.file_groupsWhereUniqueInput | Prisma.file_groupsWhereUniqueInput[]
}

export type file_groupsUncheckedCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.file_groupsCreateWithoutUsersInput, Prisma.file_groupsUncheckedCreateWithoutUsersInput> | Prisma.file_groupsCreateWithoutUsersInput[] | Prisma.file_groupsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.file_groupsCreateOrConnectWithoutUsersInput | Prisma.file_groupsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.file_groupsCreateManyUsersInputEnvelope
  connect?: Prisma.file_groupsWhereUniqueInput | Prisma.file_groupsWhereUniqueInput[]
}

export type file_groupsUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.file_groupsCreateWithoutUsersInput, Prisma.file_groupsUncheckedCreateWithoutUsersInput> | Prisma.file_groupsCreateWithoutUsersInput[] | Prisma.file_groupsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.file_groupsCreateOrConnectWithoutUsersInput | Prisma.file_groupsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.file_groupsUpsertWithWhereUniqueWithoutUsersInput | Prisma.file_groupsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.file_groupsCreateManyUsersInputEnvelope
  set?: Prisma.file_groupsWhereUniqueInput | Prisma.file_groupsWhereUniqueInput[]
  disconnect?: Prisma.file_groupsWhereUniqueInput | Prisma.file_groupsWhereUniqueInput[]
  delete?: Prisma.file_groupsWhereUniqueInput | Prisma.file_groupsWhereUniqueInput[]
  connect?: Prisma.file_groupsWhereUniqueInput | Prisma.file_groupsWhereUniqueInput[]
  update?: Prisma.file_groupsUpdateWithWhereUniqueWithoutUsersInput | Prisma.file_groupsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.file_groupsUpdateManyWithWhereWithoutUsersInput | Prisma.file_groupsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.file_groupsScalarWhereInput | Prisma.file_groupsScalarWhereInput[]
}

export type file_groupsUncheckedUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.file_groupsCreateWithoutUsersInput, Prisma.file_groupsUncheckedCreateWithoutUsersInput> | Prisma.file_groupsCreateWithoutUsersInput[] | Prisma.file_groupsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.file_groupsCreateOrConnectWithoutUsersInput | Prisma.file_groupsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.file_groupsUpsertWithWhereUniqueWithoutUsersInput | Prisma.file_groupsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.file_groupsCreateManyUsersInputEnvelope
  set?: Prisma.file_groupsWhereUniqueInput | Prisma.file_groupsWhereUniqueInput[]
  disconnect?: Prisma.file_groupsWhereUniqueInput | Prisma.file_groupsWhereUniqueInput[]
  delete?: Prisma.file_groupsWhereUniqueInput | Prisma.file_groupsWhereUniqueInput[]
  connect?: Prisma.file_groupsWhereUniqueInput | Prisma.file_groupsWhereUniqueInput[]
  update?: Prisma.file_groupsUpdateWithWhereUniqueWithoutUsersInput | Prisma.file_groupsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.file_groupsUpdateManyWithWhereWithoutUsersInput | Prisma.file_groupsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.file_groupsScalarWhereInput | Prisma.file_groupsScalarWhereInput[]
}

export type file_groupsCreateWithoutUsersInput = {
  id: string
  name: string
  file_ids: string
  created_at?: Date | string | null
}

export type file_groupsUncheckedCreateWithoutUsersInput = {
  id: string
  name: string
  file_ids: string
  created_at?: Date | string | null
}

export type file_groupsCreateOrConnectWithoutUsersInput = {
  where: Prisma.file_groupsWhereUniqueInput
  create: Prisma.XOR<Prisma.file_groupsCreateWithoutUsersInput, Prisma.file_groupsUncheckedCreateWithoutUsersInput>
}

export type file_groupsCreateManyUsersInputEnvelope = {
  data: Prisma.file_groupsCreateManyUsersInput | Prisma.file_groupsCreateManyUsersInput[]
  skipDuplicates?: boolean
}

export type file_groupsUpsertWithWhereUniqueWithoutUsersInput = {
  where: Prisma.file_groupsWhereUniqueInput
  update: Prisma.XOR<Prisma.file_groupsUpdateWithoutUsersInput, Prisma.file_groupsUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.file_groupsCreateWithoutUsersInput, Prisma.file_groupsUncheckedCreateWithoutUsersInput>
}

export type file_groupsUpdateWithWhereUniqueWithoutUsersInput = {
  where: Prisma.file_groupsWhereUniqueInput
  data: Prisma.XOR<Prisma.file_groupsUpdateWithoutUsersInput, Prisma.file_groupsUncheckedUpdateWithoutUsersInput>
}

export type file_groupsUpdateManyWithWhereWithoutUsersInput = {
  where: Prisma.file_groupsScalarWhereInput
  data: Prisma.XOR<Prisma.file_groupsUpdateManyMutationInput, Prisma.file_groupsUncheckedUpdateManyWithoutUsersInput>
}

export type file_groupsScalarWhereInput = {
  AND?: Prisma.file_groupsScalarWhereInput | Prisma.file_groupsScalarWhereInput[]
  OR?: Prisma.file_groupsScalarWhereInput[]
  NOT?: Prisma.file_groupsScalarWhereInput | Prisma.file_groupsScalarWhereInput[]
  id?: Prisma.StringFilter<"file_groups"> | string
  name?: Prisma.StringFilter<"file_groups"> | string
  file_ids?: Prisma.StringFilter<"file_groups"> | string
  user_id?: Prisma.StringFilter<"file_groups"> | string
  created_at?: Prisma.DateTimeNullableFilter<"file_groups"> | Date | string | null
}

export type file_groupsCreateManyUsersInput = {
  id: string
  name: string
  file_ids: string
  created_at?: Date | string | null
}

export type file_groupsUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  file_ids?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type file_groupsUncheckedUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  file_ids?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type file_groupsUncheckedUpdateManyWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  file_ids?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type file_groupsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  file_ids?: boolean
  user_id?: boolean
  created_at?: boolean
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["file_groups"]>



export type file_groupsSelectScalar = {
  id?: boolean
  name?: boolean
  file_ids?: boolean
  user_id?: boolean
  created_at?: boolean
}

export type file_groupsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "file_ids" | "user_id" | "created_at", ExtArgs["result"]["file_groups"]>
export type file_groupsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}

export type $file_groupsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "file_groups"
  objects: {
    users: Prisma.$usersPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    file_ids: string
    user_id: string
    created_at: Date | null
  }, ExtArgs["result"]["file_groups"]>
  composites: {}
}

export type file_groupsGetPayload<S extends boolean | null | undefined | file_groupsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$file_groupsPayload, S>

export type file_groupsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<file_groupsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: File_groupsCountAggregateInputType | true
  }

export interface file_groupsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['file_groups'], meta: { name: 'file_groups' } }
  /**
   * Find zero or one File_groups that matches the filter.
   * @param {file_groupsFindUniqueArgs} args - Arguments to find a File_groups
   * @example
   * // Get one File_groups
   * const file_groups = await prisma.file_groups.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends file_groupsFindUniqueArgs>(args: Prisma.SelectSubset<T, file_groupsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__file_groupsClient<runtime.Types.Result.GetResult<Prisma.$file_groupsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one File_groups that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {file_groupsFindUniqueOrThrowArgs} args - Arguments to find a File_groups
   * @example
   * // Get one File_groups
   * const file_groups = await prisma.file_groups.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends file_groupsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, file_groupsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__file_groupsClient<runtime.Types.Result.GetResult<Prisma.$file_groupsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first File_groups that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {file_groupsFindFirstArgs} args - Arguments to find a File_groups
   * @example
   * // Get one File_groups
   * const file_groups = await prisma.file_groups.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends file_groupsFindFirstArgs>(args?: Prisma.SelectSubset<T, file_groupsFindFirstArgs<ExtArgs>>): Prisma.Prisma__file_groupsClient<runtime.Types.Result.GetResult<Prisma.$file_groupsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first File_groups that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {file_groupsFindFirstOrThrowArgs} args - Arguments to find a File_groups
   * @example
   * // Get one File_groups
   * const file_groups = await prisma.file_groups.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends file_groupsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, file_groupsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__file_groupsClient<runtime.Types.Result.GetResult<Prisma.$file_groupsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more File_groups that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {file_groupsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all File_groups
   * const file_groups = await prisma.file_groups.findMany()
   * 
   * // Get first 10 File_groups
   * const file_groups = await prisma.file_groups.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const file_groupsWithIdOnly = await prisma.file_groups.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends file_groupsFindManyArgs>(args?: Prisma.SelectSubset<T, file_groupsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$file_groupsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a File_groups.
   * @param {file_groupsCreateArgs} args - Arguments to create a File_groups.
   * @example
   * // Create one File_groups
   * const File_groups = await prisma.file_groups.create({
   *   data: {
   *     // ... data to create a File_groups
   *   }
   * })
   * 
   */
  create<T extends file_groupsCreateArgs>(args: Prisma.SelectSubset<T, file_groupsCreateArgs<ExtArgs>>): Prisma.Prisma__file_groupsClient<runtime.Types.Result.GetResult<Prisma.$file_groupsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many File_groups.
   * @param {file_groupsCreateManyArgs} args - Arguments to create many File_groups.
   * @example
   * // Create many File_groups
   * const file_groups = await prisma.file_groups.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends file_groupsCreateManyArgs>(args?: Prisma.SelectSubset<T, file_groupsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a File_groups.
   * @param {file_groupsDeleteArgs} args - Arguments to delete one File_groups.
   * @example
   * // Delete one File_groups
   * const File_groups = await prisma.file_groups.delete({
   *   where: {
   *     // ... filter to delete one File_groups
   *   }
   * })
   * 
   */
  delete<T extends file_groupsDeleteArgs>(args: Prisma.SelectSubset<T, file_groupsDeleteArgs<ExtArgs>>): Prisma.Prisma__file_groupsClient<runtime.Types.Result.GetResult<Prisma.$file_groupsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one File_groups.
   * @param {file_groupsUpdateArgs} args - Arguments to update one File_groups.
   * @example
   * // Update one File_groups
   * const file_groups = await prisma.file_groups.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends file_groupsUpdateArgs>(args: Prisma.SelectSubset<T, file_groupsUpdateArgs<ExtArgs>>): Prisma.Prisma__file_groupsClient<runtime.Types.Result.GetResult<Prisma.$file_groupsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more File_groups.
   * @param {file_groupsDeleteManyArgs} args - Arguments to filter File_groups to delete.
   * @example
   * // Delete a few File_groups
   * const { count } = await prisma.file_groups.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends file_groupsDeleteManyArgs>(args?: Prisma.SelectSubset<T, file_groupsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more File_groups.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {file_groupsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many File_groups
   * const file_groups = await prisma.file_groups.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends file_groupsUpdateManyArgs>(args: Prisma.SelectSubset<T, file_groupsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one File_groups.
   * @param {file_groupsUpsertArgs} args - Arguments to update or create a File_groups.
   * @example
   * // Update or create a File_groups
   * const file_groups = await prisma.file_groups.upsert({
   *   create: {
   *     // ... data to create a File_groups
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the File_groups we want to update
   *   }
   * })
   */
  upsert<T extends file_groupsUpsertArgs>(args: Prisma.SelectSubset<T, file_groupsUpsertArgs<ExtArgs>>): Prisma.Prisma__file_groupsClient<runtime.Types.Result.GetResult<Prisma.$file_groupsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of File_groups.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {file_groupsCountArgs} args - Arguments to filter File_groups to count.
   * @example
   * // Count the number of File_groups
   * const count = await prisma.file_groups.count({
   *   where: {
   *     // ... the filter for the File_groups we want to count
   *   }
   * })
  **/
  count<T extends file_groupsCountArgs>(
    args?: Prisma.Subset<T, file_groupsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], File_groupsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a File_groups.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {File_groupsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends File_groupsAggregateArgs>(args: Prisma.Subset<T, File_groupsAggregateArgs>): Prisma.PrismaPromise<GetFile_groupsAggregateType<T>>

  /**
   * Group by File_groups.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {file_groupsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends file_groupsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: file_groupsGroupByArgs['orderBy'] }
      : { orderBy?: file_groupsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, file_groupsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFile_groupsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the file_groups model
 */
readonly fields: file_groupsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for file_groups.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__file_groupsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  users<T extends Prisma.usersDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.usersDefaultArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the file_groups model
 */
export interface file_groupsFieldRefs {
  readonly id: Prisma.FieldRef<"file_groups", 'String'>
  readonly name: Prisma.FieldRef<"file_groups", 'String'>
  readonly file_ids: Prisma.FieldRef<"file_groups", 'String'>
  readonly user_id: Prisma.FieldRef<"file_groups", 'String'>
  readonly created_at: Prisma.FieldRef<"file_groups", 'DateTime'>
}
    

// Custom InputTypes
/**
 * file_groups findUnique
 */
export type file_groupsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the file_groups
   */
  select?: Prisma.file_groupsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the file_groups
   */
  omit?: Prisma.file_groupsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.file_groupsInclude<ExtArgs> | null
  /**
   * Filter, which file_groups to fetch.
   */
  where: Prisma.file_groupsWhereUniqueInput
}

/**
 * file_groups findUniqueOrThrow
 */
export type file_groupsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the file_groups
   */
  select?: Prisma.file_groupsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the file_groups
   */
  omit?: Prisma.file_groupsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.file_groupsInclude<ExtArgs> | null
  /**
   * Filter, which file_groups to fetch.
   */
  where: Prisma.file_groupsWhereUniqueInput
}

/**
 * file_groups findFirst
 */
export type file_groupsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the file_groups
   */
  select?: Prisma.file_groupsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the file_groups
   */
  omit?: Prisma.file_groupsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.file_groupsInclude<ExtArgs> | null
  /**
   * Filter, which file_groups to fetch.
   */
  where?: Prisma.file_groupsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of file_groups to fetch.
   */
  orderBy?: Prisma.file_groupsOrderByWithRelationInput | Prisma.file_groupsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for file_groups.
   */
  cursor?: Prisma.file_groupsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` file_groups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` file_groups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of file_groups.
   */
  distinct?: Prisma.File_groupsScalarFieldEnum | Prisma.File_groupsScalarFieldEnum[]
}

/**
 * file_groups findFirstOrThrow
 */
export type file_groupsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the file_groups
   */
  select?: Prisma.file_groupsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the file_groups
   */
  omit?: Prisma.file_groupsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.file_groupsInclude<ExtArgs> | null
  /**
   * Filter, which file_groups to fetch.
   */
  where?: Prisma.file_groupsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of file_groups to fetch.
   */
  orderBy?: Prisma.file_groupsOrderByWithRelationInput | Prisma.file_groupsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for file_groups.
   */
  cursor?: Prisma.file_groupsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` file_groups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` file_groups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of file_groups.
   */
  distinct?: Prisma.File_groupsScalarFieldEnum | Prisma.File_groupsScalarFieldEnum[]
}

/**
 * file_groups findMany
 */
export type file_groupsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the file_groups
   */
  select?: Prisma.file_groupsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the file_groups
   */
  omit?: Prisma.file_groupsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.file_groupsInclude<ExtArgs> | null
  /**
   * Filter, which file_groups to fetch.
   */
  where?: Prisma.file_groupsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of file_groups to fetch.
   */
  orderBy?: Prisma.file_groupsOrderByWithRelationInput | Prisma.file_groupsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing file_groups.
   */
  cursor?: Prisma.file_groupsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` file_groups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` file_groups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of file_groups.
   */
  distinct?: Prisma.File_groupsScalarFieldEnum | Prisma.File_groupsScalarFieldEnum[]
}

/**
 * file_groups create
 */
export type file_groupsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the file_groups
   */
  select?: Prisma.file_groupsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the file_groups
   */
  omit?: Prisma.file_groupsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.file_groupsInclude<ExtArgs> | null
  /**
   * The data needed to create a file_groups.
   */
  data: Prisma.XOR<Prisma.file_groupsCreateInput, Prisma.file_groupsUncheckedCreateInput>
}

/**
 * file_groups createMany
 */
export type file_groupsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many file_groups.
   */
  data: Prisma.file_groupsCreateManyInput | Prisma.file_groupsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * file_groups update
 */
export type file_groupsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the file_groups
   */
  select?: Prisma.file_groupsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the file_groups
   */
  omit?: Prisma.file_groupsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.file_groupsInclude<ExtArgs> | null
  /**
   * The data needed to update a file_groups.
   */
  data: Prisma.XOR<Prisma.file_groupsUpdateInput, Prisma.file_groupsUncheckedUpdateInput>
  /**
   * Choose, which file_groups to update.
   */
  where: Prisma.file_groupsWhereUniqueInput
}

/**
 * file_groups updateMany
 */
export type file_groupsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update file_groups.
   */
  data: Prisma.XOR<Prisma.file_groupsUpdateManyMutationInput, Prisma.file_groupsUncheckedUpdateManyInput>
  /**
   * Filter which file_groups to update
   */
  where?: Prisma.file_groupsWhereInput
  /**
   * Limit how many file_groups to update.
   */
  limit?: number
}

/**
 * file_groups upsert
 */
export type file_groupsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the file_groups
   */
  select?: Prisma.file_groupsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the file_groups
   */
  omit?: Prisma.file_groupsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.file_groupsInclude<ExtArgs> | null
  /**
   * The filter to search for the file_groups to update in case it exists.
   */
  where: Prisma.file_groupsWhereUniqueInput
  /**
   * In case the file_groups found by the `where` argument doesn't exist, create a new file_groups with this data.
   */
  create: Prisma.XOR<Prisma.file_groupsCreateInput, Prisma.file_groupsUncheckedCreateInput>
  /**
   * In case the file_groups was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.file_groupsUpdateInput, Prisma.file_groupsUncheckedUpdateInput>
}

/**
 * file_groups delete
 */
export type file_groupsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the file_groups
   */
  select?: Prisma.file_groupsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the file_groups
   */
  omit?: Prisma.file_groupsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.file_groupsInclude<ExtArgs> | null
  /**
   * Filter which file_groups to delete.
   */
  where: Prisma.file_groupsWhereUniqueInput
}

/**
 * file_groups deleteMany
 */
export type file_groupsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which file_groups to delete
   */
  where?: Prisma.file_groupsWhereInput
  /**
   * Limit how many file_groups to delete.
   */
  limit?: number
}

/**
 * file_groups without action
 */
export type file_groupsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the file_groups
   */
  select?: Prisma.file_groupsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the file_groups
   */
  omit?: Prisma.file_groupsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.file_groupsInclude<ExtArgs> | null
}
