
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `file_index` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model file_index
 * 
 */
export type file_indexModel = runtime.Types.Result.DefaultSelection<Prisma.$file_indexPayload>

export type AggregateFile_index = {
  _count: File_indexCountAggregateOutputType | null
  _avg: File_indexAvgAggregateOutputType | null
  _sum: File_indexSumAggregateOutputType | null
  _min: File_indexMinAggregateOutputType | null
  _max: File_indexMaxAggregateOutputType | null
}

export type File_indexAvgAggregateOutputType = {
  visibility: number | null
  file_size_in_bytes: number | null
}

export type File_indexSumAggregateOutputType = {
  visibility: number | null
  file_size_in_bytes: bigint | null
}

export type File_indexMinAggregateOutputType = {
  id: string | null
  visibility: number | null
  date_added: Date | null
  file_size_in_bytes: bigint | null
  stored_filename: string | null
  original_name: string | null
  mime_type: string | null
  user_id: string | null
}

export type File_indexMaxAggregateOutputType = {
  id: string | null
  visibility: number | null
  date_added: Date | null
  file_size_in_bytes: bigint | null
  stored_filename: string | null
  original_name: string | null
  mime_type: string | null
  user_id: string | null
}

export type File_indexCountAggregateOutputType = {
  id: number
  visibility: number
  date_added: number
  file_size_in_bytes: number
  stored_filename: number
  original_name: number
  mime_type: number
  user_id: number
  _all: number
}


export type File_indexAvgAggregateInputType = {
  visibility?: true
  file_size_in_bytes?: true
}

export type File_indexSumAggregateInputType = {
  visibility?: true
  file_size_in_bytes?: true
}

export type File_indexMinAggregateInputType = {
  id?: true
  visibility?: true
  date_added?: true
  file_size_in_bytes?: true
  stored_filename?: true
  original_name?: true
  mime_type?: true
  user_id?: true
}

export type File_indexMaxAggregateInputType = {
  id?: true
  visibility?: true
  date_added?: true
  file_size_in_bytes?: true
  stored_filename?: true
  original_name?: true
  mime_type?: true
  user_id?: true
}

export type File_indexCountAggregateInputType = {
  id?: true
  visibility?: true
  date_added?: true
  file_size_in_bytes?: true
  stored_filename?: true
  original_name?: true
  mime_type?: true
  user_id?: true
  _all?: true
}

export type File_indexAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which file_index to aggregate.
   */
  where?: Prisma.file_indexWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of file_indices to fetch.
   */
  orderBy?: Prisma.file_indexOrderByWithRelationInput | Prisma.file_indexOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.file_indexWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` file_indices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` file_indices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned file_indices
  **/
  _count?: true | File_indexCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: File_indexAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: File_indexSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: File_indexMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: File_indexMaxAggregateInputType
}

export type GetFile_indexAggregateType<T extends File_indexAggregateArgs> = {
      [P in keyof T & keyof AggregateFile_index]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFile_index[P]>
    : Prisma.GetScalarType<T[P], AggregateFile_index[P]>
}




export type file_indexGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.file_indexWhereInput
  orderBy?: Prisma.file_indexOrderByWithAggregationInput | Prisma.file_indexOrderByWithAggregationInput[]
  by: Prisma.File_indexScalarFieldEnum[] | Prisma.File_indexScalarFieldEnum
  having?: Prisma.file_indexScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: File_indexCountAggregateInputType | true
  _avg?: File_indexAvgAggregateInputType
  _sum?: File_indexSumAggregateInputType
  _min?: File_indexMinAggregateInputType
  _max?: File_indexMaxAggregateInputType
}

export type File_indexGroupByOutputType = {
  id: string
  visibility: number
  date_added: Date | null
  file_size_in_bytes: bigint | null
  stored_filename: string
  original_name: string
  mime_type: string
  user_id: string
  _count: File_indexCountAggregateOutputType | null
  _avg: File_indexAvgAggregateOutputType | null
  _sum: File_indexSumAggregateOutputType | null
  _min: File_indexMinAggregateOutputType | null
  _max: File_indexMaxAggregateOutputType | null
}

type GetFile_indexGroupByPayload<T extends file_indexGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<File_indexGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof File_indexGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], File_indexGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], File_indexGroupByOutputType[P]>
      }
    >
  >



export type file_indexWhereInput = {
  AND?: Prisma.file_indexWhereInput | Prisma.file_indexWhereInput[]
  OR?: Prisma.file_indexWhereInput[]
  NOT?: Prisma.file_indexWhereInput | Prisma.file_indexWhereInput[]
  id?: Prisma.StringFilter<"file_index"> | string
  visibility?: Prisma.IntFilter<"file_index"> | number
  date_added?: Prisma.DateTimeNullableFilter<"file_index"> | Date | string | null
  file_size_in_bytes?: Prisma.BigIntNullableFilter<"file_index"> | bigint | number | null
  stored_filename?: Prisma.StringFilter<"file_index"> | string
  original_name?: Prisma.StringFilter<"file_index"> | string
  mime_type?: Prisma.StringFilter<"file_index"> | string
  user_id?: Prisma.StringFilter<"file_index"> | string
}

export type file_indexOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  visibility?: Prisma.SortOrder
  date_added?: Prisma.SortOrderInput | Prisma.SortOrder
  file_size_in_bytes?: Prisma.SortOrderInput | Prisma.SortOrder
  stored_filename?: Prisma.SortOrder
  original_name?: Prisma.SortOrder
  mime_type?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  _relevance?: Prisma.file_indexOrderByRelevanceInput
}

export type file_indexWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.file_indexWhereInput | Prisma.file_indexWhereInput[]
  OR?: Prisma.file_indexWhereInput[]
  NOT?: Prisma.file_indexWhereInput | Prisma.file_indexWhereInput[]
  visibility?: Prisma.IntFilter<"file_index"> | number
  date_added?: Prisma.DateTimeNullableFilter<"file_index"> | Date | string | null
  file_size_in_bytes?: Prisma.BigIntNullableFilter<"file_index"> | bigint | number | null
  stored_filename?: Prisma.StringFilter<"file_index"> | string
  original_name?: Prisma.StringFilter<"file_index"> | string
  mime_type?: Prisma.StringFilter<"file_index"> | string
  user_id?: Prisma.StringFilter<"file_index"> | string
}, "id">

export type file_indexOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  visibility?: Prisma.SortOrder
  date_added?: Prisma.SortOrderInput | Prisma.SortOrder
  file_size_in_bytes?: Prisma.SortOrderInput | Prisma.SortOrder
  stored_filename?: Prisma.SortOrder
  original_name?: Prisma.SortOrder
  mime_type?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  _count?: Prisma.file_indexCountOrderByAggregateInput
  _avg?: Prisma.file_indexAvgOrderByAggregateInput
  _max?: Prisma.file_indexMaxOrderByAggregateInput
  _min?: Prisma.file_indexMinOrderByAggregateInput
  _sum?: Prisma.file_indexSumOrderByAggregateInput
}

export type file_indexScalarWhereWithAggregatesInput = {
  AND?: Prisma.file_indexScalarWhereWithAggregatesInput | Prisma.file_indexScalarWhereWithAggregatesInput[]
  OR?: Prisma.file_indexScalarWhereWithAggregatesInput[]
  NOT?: Prisma.file_indexScalarWhereWithAggregatesInput | Prisma.file_indexScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"file_index"> | string
  visibility?: Prisma.IntWithAggregatesFilter<"file_index"> | number
  date_added?: Prisma.DateTimeNullableWithAggregatesFilter<"file_index"> | Date | string | null
  file_size_in_bytes?: Prisma.BigIntNullableWithAggregatesFilter<"file_index"> | bigint | number | null
  stored_filename?: Prisma.StringWithAggregatesFilter<"file_index"> | string
  original_name?: Prisma.StringWithAggregatesFilter<"file_index"> | string
  mime_type?: Prisma.StringWithAggregatesFilter<"file_index"> | string
  user_id?: Prisma.StringWithAggregatesFilter<"file_index"> | string
}

export type file_indexCreateInput = {
  id: string
  visibility?: number
  date_added?: Date | string | null
  file_size_in_bytes?: bigint | number | null
  stored_filename: string
  original_name: string
  mime_type: string
  user_id: string
}

export type file_indexUncheckedCreateInput = {
  id: string
  visibility?: number
  date_added?: Date | string | null
  file_size_in_bytes?: bigint | number | null
  stored_filename: string
  original_name: string
  mime_type: string
  user_id: string
}

export type file_indexUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  visibility?: Prisma.IntFieldUpdateOperationsInput | number
  date_added?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  file_size_in_bytes?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  stored_filename?: Prisma.StringFieldUpdateOperationsInput | string
  original_name?: Prisma.StringFieldUpdateOperationsInput | string
  mime_type?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type file_indexUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  visibility?: Prisma.IntFieldUpdateOperationsInput | number
  date_added?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  file_size_in_bytes?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  stored_filename?: Prisma.StringFieldUpdateOperationsInput | string
  original_name?: Prisma.StringFieldUpdateOperationsInput | string
  mime_type?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type file_indexCreateManyInput = {
  id: string
  visibility?: number
  date_added?: Date | string | null
  file_size_in_bytes?: bigint | number | null
  stored_filename: string
  original_name: string
  mime_type: string
  user_id: string
}

export type file_indexUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  visibility?: Prisma.IntFieldUpdateOperationsInput | number
  date_added?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  file_size_in_bytes?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  stored_filename?: Prisma.StringFieldUpdateOperationsInput | string
  original_name?: Prisma.StringFieldUpdateOperationsInput | string
  mime_type?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type file_indexUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  visibility?: Prisma.IntFieldUpdateOperationsInput | number
  date_added?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  file_size_in_bytes?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  stored_filename?: Prisma.StringFieldUpdateOperationsInput | string
  original_name?: Prisma.StringFieldUpdateOperationsInput | string
  mime_type?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type file_indexOrderByRelevanceInput = {
  fields: Prisma.file_indexOrderByRelevanceFieldEnum | Prisma.file_indexOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type file_indexCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  visibility?: Prisma.SortOrder
  date_added?: Prisma.SortOrder
  file_size_in_bytes?: Prisma.SortOrder
  stored_filename?: Prisma.SortOrder
  original_name?: Prisma.SortOrder
  mime_type?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
}

export type file_indexAvgOrderByAggregateInput = {
  visibility?: Prisma.SortOrder
  file_size_in_bytes?: Prisma.SortOrder
}

export type file_indexMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  visibility?: Prisma.SortOrder
  date_added?: Prisma.SortOrder
  file_size_in_bytes?: Prisma.SortOrder
  stored_filename?: Prisma.SortOrder
  original_name?: Prisma.SortOrder
  mime_type?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
}

export type file_indexMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  visibility?: Prisma.SortOrder
  date_added?: Prisma.SortOrder
  file_size_in_bytes?: Prisma.SortOrder
  stored_filename?: Prisma.SortOrder
  original_name?: Prisma.SortOrder
  mime_type?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
}

export type file_indexSumOrderByAggregateInput = {
  visibility?: Prisma.SortOrder
  file_size_in_bytes?: Prisma.SortOrder
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableBigIntFieldUpdateOperationsInput = {
  set?: bigint | number | null
  increment?: bigint | number
  decrement?: bigint | number
  multiply?: bigint | number
  divide?: bigint | number
}



export type file_indexSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  visibility?: boolean
  date_added?: boolean
  file_size_in_bytes?: boolean
  stored_filename?: boolean
  original_name?: boolean
  mime_type?: boolean
  user_id?: boolean
}, ExtArgs["result"]["file_index"]>



export type file_indexSelectScalar = {
  id?: boolean
  visibility?: boolean
  date_added?: boolean
  file_size_in_bytes?: boolean
  stored_filename?: boolean
  original_name?: boolean
  mime_type?: boolean
  user_id?: boolean
}

export type file_indexOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "visibility" | "date_added" | "file_size_in_bytes" | "stored_filename" | "original_name" | "mime_type" | "user_id", ExtArgs["result"]["file_index"]>

export type $file_indexPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "file_index"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    visibility: number
    date_added: Date | null
    file_size_in_bytes: bigint | null
    stored_filename: string
    original_name: string
    mime_type: string
    user_id: string
  }, ExtArgs["result"]["file_index"]>
  composites: {}
}

export type file_indexGetPayload<S extends boolean | null | undefined | file_indexDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$file_indexPayload, S>

export type file_indexCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<file_indexFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: File_indexCountAggregateInputType | true
  }

export interface file_indexDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['file_index'], meta: { name: 'file_index' } }
  /**
   * Find zero or one File_index that matches the filter.
   * @param {file_indexFindUniqueArgs} args - Arguments to find a File_index
   * @example
   * // Get one File_index
   * const file_index = await prisma.file_index.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends file_indexFindUniqueArgs>(args: Prisma.SelectSubset<T, file_indexFindUniqueArgs<ExtArgs>>): Prisma.Prisma__file_indexClient<runtime.Types.Result.GetResult<Prisma.$file_indexPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one File_index that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {file_indexFindUniqueOrThrowArgs} args - Arguments to find a File_index
   * @example
   * // Get one File_index
   * const file_index = await prisma.file_index.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends file_indexFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, file_indexFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__file_indexClient<runtime.Types.Result.GetResult<Prisma.$file_indexPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first File_index that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {file_indexFindFirstArgs} args - Arguments to find a File_index
   * @example
   * // Get one File_index
   * const file_index = await prisma.file_index.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends file_indexFindFirstArgs>(args?: Prisma.SelectSubset<T, file_indexFindFirstArgs<ExtArgs>>): Prisma.Prisma__file_indexClient<runtime.Types.Result.GetResult<Prisma.$file_indexPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first File_index that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {file_indexFindFirstOrThrowArgs} args - Arguments to find a File_index
   * @example
   * // Get one File_index
   * const file_index = await prisma.file_index.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends file_indexFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, file_indexFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__file_indexClient<runtime.Types.Result.GetResult<Prisma.$file_indexPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more File_indices that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {file_indexFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all File_indices
   * const file_indices = await prisma.file_index.findMany()
   * 
   * // Get first 10 File_indices
   * const file_indices = await prisma.file_index.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const file_indexWithIdOnly = await prisma.file_index.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends file_indexFindManyArgs>(args?: Prisma.SelectSubset<T, file_indexFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$file_indexPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a File_index.
   * @param {file_indexCreateArgs} args - Arguments to create a File_index.
   * @example
   * // Create one File_index
   * const File_index = await prisma.file_index.create({
   *   data: {
   *     // ... data to create a File_index
   *   }
   * })
   * 
   */
  create<T extends file_indexCreateArgs>(args: Prisma.SelectSubset<T, file_indexCreateArgs<ExtArgs>>): Prisma.Prisma__file_indexClient<runtime.Types.Result.GetResult<Prisma.$file_indexPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many File_indices.
   * @param {file_indexCreateManyArgs} args - Arguments to create many File_indices.
   * @example
   * // Create many File_indices
   * const file_index = await prisma.file_index.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends file_indexCreateManyArgs>(args?: Prisma.SelectSubset<T, file_indexCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a File_index.
   * @param {file_indexDeleteArgs} args - Arguments to delete one File_index.
   * @example
   * // Delete one File_index
   * const File_index = await prisma.file_index.delete({
   *   where: {
   *     // ... filter to delete one File_index
   *   }
   * })
   * 
   */
  delete<T extends file_indexDeleteArgs>(args: Prisma.SelectSubset<T, file_indexDeleteArgs<ExtArgs>>): Prisma.Prisma__file_indexClient<runtime.Types.Result.GetResult<Prisma.$file_indexPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one File_index.
   * @param {file_indexUpdateArgs} args - Arguments to update one File_index.
   * @example
   * // Update one File_index
   * const file_index = await prisma.file_index.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends file_indexUpdateArgs>(args: Prisma.SelectSubset<T, file_indexUpdateArgs<ExtArgs>>): Prisma.Prisma__file_indexClient<runtime.Types.Result.GetResult<Prisma.$file_indexPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more File_indices.
   * @param {file_indexDeleteManyArgs} args - Arguments to filter File_indices to delete.
   * @example
   * // Delete a few File_indices
   * const { count } = await prisma.file_index.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends file_indexDeleteManyArgs>(args?: Prisma.SelectSubset<T, file_indexDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more File_indices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {file_indexUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many File_indices
   * const file_index = await prisma.file_index.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends file_indexUpdateManyArgs>(args: Prisma.SelectSubset<T, file_indexUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one File_index.
   * @param {file_indexUpsertArgs} args - Arguments to update or create a File_index.
   * @example
   * // Update or create a File_index
   * const file_index = await prisma.file_index.upsert({
   *   create: {
   *     // ... data to create a File_index
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the File_index we want to update
   *   }
   * })
   */
  upsert<T extends file_indexUpsertArgs>(args: Prisma.SelectSubset<T, file_indexUpsertArgs<ExtArgs>>): Prisma.Prisma__file_indexClient<runtime.Types.Result.GetResult<Prisma.$file_indexPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of File_indices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {file_indexCountArgs} args - Arguments to filter File_indices to count.
   * @example
   * // Count the number of File_indices
   * const count = await prisma.file_index.count({
   *   where: {
   *     // ... the filter for the File_indices we want to count
   *   }
   * })
  **/
  count<T extends file_indexCountArgs>(
    args?: Prisma.Subset<T, file_indexCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], File_indexCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a File_index.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {File_indexAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends File_indexAggregateArgs>(args: Prisma.Subset<T, File_indexAggregateArgs>): Prisma.PrismaPromise<GetFile_indexAggregateType<T>>

  /**
   * Group by File_index.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {file_indexGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends file_indexGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: file_indexGroupByArgs['orderBy'] }
      : { orderBy?: file_indexGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, file_indexGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFile_indexGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the file_index model
 */
readonly fields: file_indexFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for file_index.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__file_indexClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the file_index model
 */
export interface file_indexFieldRefs {
  readonly id: Prisma.FieldRef<"file_index", 'String'>
  readonly visibility: Prisma.FieldRef<"file_index", 'Int'>
  readonly date_added: Prisma.FieldRef<"file_index", 'DateTime'>
  readonly file_size_in_bytes: Prisma.FieldRef<"file_index", 'BigInt'>
  readonly stored_filename: Prisma.FieldRef<"file_index", 'String'>
  readonly original_name: Prisma.FieldRef<"file_index", 'String'>
  readonly mime_type: Prisma.FieldRef<"file_index", 'String'>
  readonly user_id: Prisma.FieldRef<"file_index", 'String'>
}
    

// Custom InputTypes
/**
 * file_index findUnique
 */
export type file_indexFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the file_index
   */
  select?: Prisma.file_indexSelect<ExtArgs> | null
  /**
   * Omit specific fields from the file_index
   */
  omit?: Prisma.file_indexOmit<ExtArgs> | null
  /**
   * Filter, which file_index to fetch.
   */
  where: Prisma.file_indexWhereUniqueInput
}

/**
 * file_index findUniqueOrThrow
 */
export type file_indexFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the file_index
   */
  select?: Prisma.file_indexSelect<ExtArgs> | null
  /**
   * Omit specific fields from the file_index
   */
  omit?: Prisma.file_indexOmit<ExtArgs> | null
  /**
   * Filter, which file_index to fetch.
   */
  where: Prisma.file_indexWhereUniqueInput
}

/**
 * file_index findFirst
 */
export type file_indexFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the file_index
   */
  select?: Prisma.file_indexSelect<ExtArgs> | null
  /**
   * Omit specific fields from the file_index
   */
  omit?: Prisma.file_indexOmit<ExtArgs> | null
  /**
   * Filter, which file_index to fetch.
   */
  where?: Prisma.file_indexWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of file_indices to fetch.
   */
  orderBy?: Prisma.file_indexOrderByWithRelationInput | Prisma.file_indexOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for file_indices.
   */
  cursor?: Prisma.file_indexWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` file_indices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` file_indices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of file_indices.
   */
  distinct?: Prisma.File_indexScalarFieldEnum | Prisma.File_indexScalarFieldEnum[]
}

/**
 * file_index findFirstOrThrow
 */
export type file_indexFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the file_index
   */
  select?: Prisma.file_indexSelect<ExtArgs> | null
  /**
   * Omit specific fields from the file_index
   */
  omit?: Prisma.file_indexOmit<ExtArgs> | null
  /**
   * Filter, which file_index to fetch.
   */
  where?: Prisma.file_indexWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of file_indices to fetch.
   */
  orderBy?: Prisma.file_indexOrderByWithRelationInput | Prisma.file_indexOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for file_indices.
   */
  cursor?: Prisma.file_indexWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` file_indices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` file_indices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of file_indices.
   */
  distinct?: Prisma.File_indexScalarFieldEnum | Prisma.File_indexScalarFieldEnum[]
}

/**
 * file_index findMany
 */
export type file_indexFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the file_index
   */
  select?: Prisma.file_indexSelect<ExtArgs> | null
  /**
   * Omit specific fields from the file_index
   */
  omit?: Prisma.file_indexOmit<ExtArgs> | null
  /**
   * Filter, which file_indices to fetch.
   */
  where?: Prisma.file_indexWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of file_indices to fetch.
   */
  orderBy?: Prisma.file_indexOrderByWithRelationInput | Prisma.file_indexOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing file_indices.
   */
  cursor?: Prisma.file_indexWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` file_indices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` file_indices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of file_indices.
   */
  distinct?: Prisma.File_indexScalarFieldEnum | Prisma.File_indexScalarFieldEnum[]
}

/**
 * file_index create
 */
export type file_indexCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the file_index
   */
  select?: Prisma.file_indexSelect<ExtArgs> | null
  /**
   * Omit specific fields from the file_index
   */
  omit?: Prisma.file_indexOmit<ExtArgs> | null
  /**
   * The data needed to create a file_index.
   */
  data: Prisma.XOR<Prisma.file_indexCreateInput, Prisma.file_indexUncheckedCreateInput>
}

/**
 * file_index createMany
 */
export type file_indexCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many file_indices.
   */
  data: Prisma.file_indexCreateManyInput | Prisma.file_indexCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * file_index update
 */
export type file_indexUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the file_index
   */
  select?: Prisma.file_indexSelect<ExtArgs> | null
  /**
   * Omit specific fields from the file_index
   */
  omit?: Prisma.file_indexOmit<ExtArgs> | null
  /**
   * The data needed to update a file_index.
   */
  data: Prisma.XOR<Prisma.file_indexUpdateInput, Prisma.file_indexUncheckedUpdateInput>
  /**
   * Choose, which file_index to update.
   */
  where: Prisma.file_indexWhereUniqueInput
}

/**
 * file_index updateMany
 */
export type file_indexUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update file_indices.
   */
  data: Prisma.XOR<Prisma.file_indexUpdateManyMutationInput, Prisma.file_indexUncheckedUpdateManyInput>
  /**
   * Filter which file_indices to update
   */
  where?: Prisma.file_indexWhereInput
  /**
   * Limit how many file_indices to update.
   */
  limit?: number
}

/**
 * file_index upsert
 */
export type file_indexUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the file_index
   */
  select?: Prisma.file_indexSelect<ExtArgs> | null
  /**
   * Omit specific fields from the file_index
   */
  omit?: Prisma.file_indexOmit<ExtArgs> | null
  /**
   * The filter to search for the file_index to update in case it exists.
   */
  where: Prisma.file_indexWhereUniqueInput
  /**
   * In case the file_index found by the `where` argument doesn't exist, create a new file_index with this data.
   */
  create: Prisma.XOR<Prisma.file_indexCreateInput, Prisma.file_indexUncheckedCreateInput>
  /**
   * In case the file_index was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.file_indexUpdateInput, Prisma.file_indexUncheckedUpdateInput>
}

/**
 * file_index delete
 */
export type file_indexDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the file_index
   */
  select?: Prisma.file_indexSelect<ExtArgs> | null
  /**
   * Omit specific fields from the file_index
   */
  omit?: Prisma.file_indexOmit<ExtArgs> | null
  /**
   * Filter which file_index to delete.
   */
  where: Prisma.file_indexWhereUniqueInput
}

/**
 * file_index deleteMany
 */
export type file_indexDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which file_indices to delete
   */
  where?: Prisma.file_indexWhereInput
  /**
   * Limit how many file_indices to delete.
   */
  limit?: number
}

/**
 * file_index without action
 */
export type file_indexDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the file_index
   */
  select?: Prisma.file_indexSelect<ExtArgs> | null
  /**
   * Omit specific fields from the file_index
   */
  omit?: Prisma.file_indexOmit<ExtArgs> | null
}
