
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `session_tokens` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model session_tokens
 * 
 */
export type session_tokensModel = runtime.Types.Result.DefaultSelection<Prisma.$session_tokensPayload>

export type AggregateSession_tokens = {
  _count: Session_tokensCountAggregateOutputType | null
  _min: Session_tokensMinAggregateOutputType | null
  _max: Session_tokensMaxAggregateOutputType | null
}

export type Session_tokensMinAggregateOutputType = {
  token: string | null
  user_id: string | null
  is_valid: boolean | null
  user_agent: string | null
  added_on: Date | null
}

export type Session_tokensMaxAggregateOutputType = {
  token: string | null
  user_id: string | null
  is_valid: boolean | null
  user_agent: string | null
  added_on: Date | null
}

export type Session_tokensCountAggregateOutputType = {
  token: number
  user_id: number
  is_valid: number
  user_agent: number
  added_on: number
  _all: number
}


export type Session_tokensMinAggregateInputType = {
  token?: true
  user_id?: true
  is_valid?: true
  user_agent?: true
  added_on?: true
}

export type Session_tokensMaxAggregateInputType = {
  token?: true
  user_id?: true
  is_valid?: true
  user_agent?: true
  added_on?: true
}

export type Session_tokensCountAggregateInputType = {
  token?: true
  user_id?: true
  is_valid?: true
  user_agent?: true
  added_on?: true
  _all?: true
}

export type Session_tokensAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which session_tokens to aggregate.
   */
  where?: Prisma.session_tokensWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of session_tokens to fetch.
   */
  orderBy?: Prisma.session_tokensOrderByWithRelationInput | Prisma.session_tokensOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.session_tokensWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` session_tokens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` session_tokens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned session_tokens
  **/
  _count?: true | Session_tokensCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Session_tokensMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Session_tokensMaxAggregateInputType
}

export type GetSession_tokensAggregateType<T extends Session_tokensAggregateArgs> = {
      [P in keyof T & keyof AggregateSession_tokens]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSession_tokens[P]>
    : Prisma.GetScalarType<T[P], AggregateSession_tokens[P]>
}




export type session_tokensGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.session_tokensWhereInput
  orderBy?: Prisma.session_tokensOrderByWithAggregationInput | Prisma.session_tokensOrderByWithAggregationInput[]
  by: Prisma.Session_tokensScalarFieldEnum[] | Prisma.Session_tokensScalarFieldEnum
  having?: Prisma.session_tokensScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Session_tokensCountAggregateInputType | true
  _min?: Session_tokensMinAggregateInputType
  _max?: Session_tokensMaxAggregateInputType
}

export type Session_tokensGroupByOutputType = {
  token: string
  user_id: string
  is_valid: boolean | null
  user_agent: string | null
  added_on: Date | null
  _count: Session_tokensCountAggregateOutputType | null
  _min: Session_tokensMinAggregateOutputType | null
  _max: Session_tokensMaxAggregateOutputType | null
}

type GetSession_tokensGroupByPayload<T extends session_tokensGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Session_tokensGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Session_tokensGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Session_tokensGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Session_tokensGroupByOutputType[P]>
      }
    >
  >



export type session_tokensWhereInput = {
  AND?: Prisma.session_tokensWhereInput | Prisma.session_tokensWhereInput[]
  OR?: Prisma.session_tokensWhereInput[]
  NOT?: Prisma.session_tokensWhereInput | Prisma.session_tokensWhereInput[]
  token?: Prisma.StringFilter<"session_tokens"> | string
  user_id?: Prisma.StringFilter<"session_tokens"> | string
  is_valid?: Prisma.BoolNullableFilter<"session_tokens"> | boolean | null
  user_agent?: Prisma.StringNullableFilter<"session_tokens"> | string | null
  added_on?: Prisma.DateTimeNullableFilter<"session_tokens"> | Date | string | null
}

export type session_tokensOrderByWithRelationInput = {
  token?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  is_valid?: Prisma.SortOrderInput | Prisma.SortOrder
  user_agent?: Prisma.SortOrderInput | Prisma.SortOrder
  added_on?: Prisma.SortOrderInput | Prisma.SortOrder
  _relevance?: Prisma.session_tokensOrderByRelevanceInput
}

export type session_tokensWhereUniqueInput = Prisma.AtLeast<{
  token?: string
  AND?: Prisma.session_tokensWhereInput | Prisma.session_tokensWhereInput[]
  OR?: Prisma.session_tokensWhereInput[]
  NOT?: Prisma.session_tokensWhereInput | Prisma.session_tokensWhereInput[]
  user_id?: Prisma.StringFilter<"session_tokens"> | string
  is_valid?: Prisma.BoolNullableFilter<"session_tokens"> | boolean | null
  user_agent?: Prisma.StringNullableFilter<"session_tokens"> | string | null
  added_on?: Prisma.DateTimeNullableFilter<"session_tokens"> | Date | string | null
}, "token">

export type session_tokensOrderByWithAggregationInput = {
  token?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  is_valid?: Prisma.SortOrderInput | Prisma.SortOrder
  user_agent?: Prisma.SortOrderInput | Prisma.SortOrder
  added_on?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.session_tokensCountOrderByAggregateInput
  _max?: Prisma.session_tokensMaxOrderByAggregateInput
  _min?: Prisma.session_tokensMinOrderByAggregateInput
}

export type session_tokensScalarWhereWithAggregatesInput = {
  AND?: Prisma.session_tokensScalarWhereWithAggregatesInput | Prisma.session_tokensScalarWhereWithAggregatesInput[]
  OR?: Prisma.session_tokensScalarWhereWithAggregatesInput[]
  NOT?: Prisma.session_tokensScalarWhereWithAggregatesInput | Prisma.session_tokensScalarWhereWithAggregatesInput[]
  token?: Prisma.StringWithAggregatesFilter<"session_tokens"> | string
  user_id?: Prisma.StringWithAggregatesFilter<"session_tokens"> | string
  is_valid?: Prisma.BoolNullableWithAggregatesFilter<"session_tokens"> | boolean | null
  user_agent?: Prisma.StringNullableWithAggregatesFilter<"session_tokens"> | string | null
  added_on?: Prisma.DateTimeNullableWithAggregatesFilter<"session_tokens"> | Date | string | null
}

export type session_tokensCreateInput = {
  token: string
  user_id: string
  is_valid?: boolean | null
  user_agent?: string | null
  added_on?: Date | string | null
}

export type session_tokensUncheckedCreateInput = {
  token: string
  user_id: string
  is_valid?: boolean | null
  user_agent?: string | null
  added_on?: Date | string | null
}

export type session_tokensUpdateInput = {
  token?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  is_valid?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  user_agent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  added_on?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type session_tokensUncheckedUpdateInput = {
  token?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  is_valid?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  user_agent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  added_on?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type session_tokensCreateManyInput = {
  token: string
  user_id: string
  is_valid?: boolean | null
  user_agent?: string | null
  added_on?: Date | string | null
}

export type session_tokensUpdateManyMutationInput = {
  token?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  is_valid?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  user_agent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  added_on?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type session_tokensUncheckedUpdateManyInput = {
  token?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  is_valid?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  user_agent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  added_on?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type session_tokensOrderByRelevanceInput = {
  fields: Prisma.session_tokensOrderByRelevanceFieldEnum | Prisma.session_tokensOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type session_tokensCountOrderByAggregateInput = {
  token?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  is_valid?: Prisma.SortOrder
  user_agent?: Prisma.SortOrder
  added_on?: Prisma.SortOrder
}

export type session_tokensMaxOrderByAggregateInput = {
  token?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  is_valid?: Prisma.SortOrder
  user_agent?: Prisma.SortOrder
  added_on?: Prisma.SortOrder
}

export type session_tokensMinOrderByAggregateInput = {
  token?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  is_valid?: Prisma.SortOrder
  user_agent?: Prisma.SortOrder
  added_on?: Prisma.SortOrder
}

export type NullableBoolFieldUpdateOperationsInput = {
  set?: boolean | null
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}



export type session_tokensSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  token?: boolean
  user_id?: boolean
  is_valid?: boolean
  user_agent?: boolean
  added_on?: boolean
}, ExtArgs["result"]["session_tokens"]>



export type session_tokensSelectScalar = {
  token?: boolean
  user_id?: boolean
  is_valid?: boolean
  user_agent?: boolean
  added_on?: boolean
}

export type session_tokensOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"token" | "user_id" | "is_valid" | "user_agent" | "added_on", ExtArgs["result"]["session_tokens"]>

export type $session_tokensPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "session_tokens"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    token: string
    user_id: string
    is_valid: boolean | null
    user_agent: string | null
    added_on: Date | null
  }, ExtArgs["result"]["session_tokens"]>
  composites: {}
}

export type session_tokensGetPayload<S extends boolean | null | undefined | session_tokensDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$session_tokensPayload, S>

export type session_tokensCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<session_tokensFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Session_tokensCountAggregateInputType | true
  }

export interface session_tokensDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['session_tokens'], meta: { name: 'session_tokens' } }
  /**
   * Find zero or one Session_tokens that matches the filter.
   * @param {session_tokensFindUniqueArgs} args - Arguments to find a Session_tokens
   * @example
   * // Get one Session_tokens
   * const session_tokens = await prisma.session_tokens.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends session_tokensFindUniqueArgs>(args: Prisma.SelectSubset<T, session_tokensFindUniqueArgs<ExtArgs>>): Prisma.Prisma__session_tokensClient<runtime.Types.Result.GetResult<Prisma.$session_tokensPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Session_tokens that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {session_tokensFindUniqueOrThrowArgs} args - Arguments to find a Session_tokens
   * @example
   * // Get one Session_tokens
   * const session_tokens = await prisma.session_tokens.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends session_tokensFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, session_tokensFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__session_tokensClient<runtime.Types.Result.GetResult<Prisma.$session_tokensPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Session_tokens that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {session_tokensFindFirstArgs} args - Arguments to find a Session_tokens
   * @example
   * // Get one Session_tokens
   * const session_tokens = await prisma.session_tokens.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends session_tokensFindFirstArgs>(args?: Prisma.SelectSubset<T, session_tokensFindFirstArgs<ExtArgs>>): Prisma.Prisma__session_tokensClient<runtime.Types.Result.GetResult<Prisma.$session_tokensPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Session_tokens that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {session_tokensFindFirstOrThrowArgs} args - Arguments to find a Session_tokens
   * @example
   * // Get one Session_tokens
   * const session_tokens = await prisma.session_tokens.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends session_tokensFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, session_tokensFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__session_tokensClient<runtime.Types.Result.GetResult<Prisma.$session_tokensPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Session_tokens that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {session_tokensFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Session_tokens
   * const session_tokens = await prisma.session_tokens.findMany()
   * 
   * // Get first 10 Session_tokens
   * const session_tokens = await prisma.session_tokens.findMany({ take: 10 })
   * 
   * // Only select the `token`
   * const session_tokensWithTokenOnly = await prisma.session_tokens.findMany({ select: { token: true } })
   * 
   */
  findMany<T extends session_tokensFindManyArgs>(args?: Prisma.SelectSubset<T, session_tokensFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$session_tokensPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Session_tokens.
   * @param {session_tokensCreateArgs} args - Arguments to create a Session_tokens.
   * @example
   * // Create one Session_tokens
   * const Session_tokens = await prisma.session_tokens.create({
   *   data: {
   *     // ... data to create a Session_tokens
   *   }
   * })
   * 
   */
  create<T extends session_tokensCreateArgs>(args: Prisma.SelectSubset<T, session_tokensCreateArgs<ExtArgs>>): Prisma.Prisma__session_tokensClient<runtime.Types.Result.GetResult<Prisma.$session_tokensPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Session_tokens.
   * @param {session_tokensCreateManyArgs} args - Arguments to create many Session_tokens.
   * @example
   * // Create many Session_tokens
   * const session_tokens = await prisma.session_tokens.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends session_tokensCreateManyArgs>(args?: Prisma.SelectSubset<T, session_tokensCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Session_tokens.
   * @param {session_tokensDeleteArgs} args - Arguments to delete one Session_tokens.
   * @example
   * // Delete one Session_tokens
   * const Session_tokens = await prisma.session_tokens.delete({
   *   where: {
   *     // ... filter to delete one Session_tokens
   *   }
   * })
   * 
   */
  delete<T extends session_tokensDeleteArgs>(args: Prisma.SelectSubset<T, session_tokensDeleteArgs<ExtArgs>>): Prisma.Prisma__session_tokensClient<runtime.Types.Result.GetResult<Prisma.$session_tokensPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Session_tokens.
   * @param {session_tokensUpdateArgs} args - Arguments to update one Session_tokens.
   * @example
   * // Update one Session_tokens
   * const session_tokens = await prisma.session_tokens.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends session_tokensUpdateArgs>(args: Prisma.SelectSubset<T, session_tokensUpdateArgs<ExtArgs>>): Prisma.Prisma__session_tokensClient<runtime.Types.Result.GetResult<Prisma.$session_tokensPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Session_tokens.
   * @param {session_tokensDeleteManyArgs} args - Arguments to filter Session_tokens to delete.
   * @example
   * // Delete a few Session_tokens
   * const { count } = await prisma.session_tokens.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends session_tokensDeleteManyArgs>(args?: Prisma.SelectSubset<T, session_tokensDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Session_tokens.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {session_tokensUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Session_tokens
   * const session_tokens = await prisma.session_tokens.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends session_tokensUpdateManyArgs>(args: Prisma.SelectSubset<T, session_tokensUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Session_tokens.
   * @param {session_tokensUpsertArgs} args - Arguments to update or create a Session_tokens.
   * @example
   * // Update or create a Session_tokens
   * const session_tokens = await prisma.session_tokens.upsert({
   *   create: {
   *     // ... data to create a Session_tokens
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Session_tokens we want to update
   *   }
   * })
   */
  upsert<T extends session_tokensUpsertArgs>(args: Prisma.SelectSubset<T, session_tokensUpsertArgs<ExtArgs>>): Prisma.Prisma__session_tokensClient<runtime.Types.Result.GetResult<Prisma.$session_tokensPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Session_tokens.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {session_tokensCountArgs} args - Arguments to filter Session_tokens to count.
   * @example
   * // Count the number of Session_tokens
   * const count = await prisma.session_tokens.count({
   *   where: {
   *     // ... the filter for the Session_tokens we want to count
   *   }
   * })
  **/
  count<T extends session_tokensCountArgs>(
    args?: Prisma.Subset<T, session_tokensCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Session_tokensCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Session_tokens.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Session_tokensAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Session_tokensAggregateArgs>(args: Prisma.Subset<T, Session_tokensAggregateArgs>): Prisma.PrismaPromise<GetSession_tokensAggregateType<T>>

  /**
   * Group by Session_tokens.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {session_tokensGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends session_tokensGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: session_tokensGroupByArgs['orderBy'] }
      : { orderBy?: session_tokensGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, session_tokensGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSession_tokensGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the session_tokens model
 */
readonly fields: session_tokensFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for session_tokens.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__session_tokensClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the session_tokens model
 */
export interface session_tokensFieldRefs {
  readonly token: Prisma.FieldRef<"session_tokens", 'String'>
  readonly user_id: Prisma.FieldRef<"session_tokens", 'String'>
  readonly is_valid: Prisma.FieldRef<"session_tokens", 'Boolean'>
  readonly user_agent: Prisma.FieldRef<"session_tokens", 'String'>
  readonly added_on: Prisma.FieldRef<"session_tokens", 'DateTime'>
}
    

// Custom InputTypes
/**
 * session_tokens findUnique
 */
export type session_tokensFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the session_tokens
   */
  select?: Prisma.session_tokensSelect<ExtArgs> | null
  /**
   * Omit specific fields from the session_tokens
   */
  omit?: Prisma.session_tokensOmit<ExtArgs> | null
  /**
   * Filter, which session_tokens to fetch.
   */
  where: Prisma.session_tokensWhereUniqueInput
}

/**
 * session_tokens findUniqueOrThrow
 */
export type session_tokensFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the session_tokens
   */
  select?: Prisma.session_tokensSelect<ExtArgs> | null
  /**
   * Omit specific fields from the session_tokens
   */
  omit?: Prisma.session_tokensOmit<ExtArgs> | null
  /**
   * Filter, which session_tokens to fetch.
   */
  where: Prisma.session_tokensWhereUniqueInput
}

/**
 * session_tokens findFirst
 */
export type session_tokensFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the session_tokens
   */
  select?: Prisma.session_tokensSelect<ExtArgs> | null
  /**
   * Omit specific fields from the session_tokens
   */
  omit?: Prisma.session_tokensOmit<ExtArgs> | null
  /**
   * Filter, which session_tokens to fetch.
   */
  where?: Prisma.session_tokensWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of session_tokens to fetch.
   */
  orderBy?: Prisma.session_tokensOrderByWithRelationInput | Prisma.session_tokensOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for session_tokens.
   */
  cursor?: Prisma.session_tokensWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` session_tokens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` session_tokens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of session_tokens.
   */
  distinct?: Prisma.Session_tokensScalarFieldEnum | Prisma.Session_tokensScalarFieldEnum[]
}

/**
 * session_tokens findFirstOrThrow
 */
export type session_tokensFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the session_tokens
   */
  select?: Prisma.session_tokensSelect<ExtArgs> | null
  /**
   * Omit specific fields from the session_tokens
   */
  omit?: Prisma.session_tokensOmit<ExtArgs> | null
  /**
   * Filter, which session_tokens to fetch.
   */
  where?: Prisma.session_tokensWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of session_tokens to fetch.
   */
  orderBy?: Prisma.session_tokensOrderByWithRelationInput | Prisma.session_tokensOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for session_tokens.
   */
  cursor?: Prisma.session_tokensWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` session_tokens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` session_tokens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of session_tokens.
   */
  distinct?: Prisma.Session_tokensScalarFieldEnum | Prisma.Session_tokensScalarFieldEnum[]
}

/**
 * session_tokens findMany
 */
export type session_tokensFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the session_tokens
   */
  select?: Prisma.session_tokensSelect<ExtArgs> | null
  /**
   * Omit specific fields from the session_tokens
   */
  omit?: Prisma.session_tokensOmit<ExtArgs> | null
  /**
   * Filter, which session_tokens to fetch.
   */
  where?: Prisma.session_tokensWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of session_tokens to fetch.
   */
  orderBy?: Prisma.session_tokensOrderByWithRelationInput | Prisma.session_tokensOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing session_tokens.
   */
  cursor?: Prisma.session_tokensWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` session_tokens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` session_tokens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of session_tokens.
   */
  distinct?: Prisma.Session_tokensScalarFieldEnum | Prisma.Session_tokensScalarFieldEnum[]
}

/**
 * session_tokens create
 */
export type session_tokensCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the session_tokens
   */
  select?: Prisma.session_tokensSelect<ExtArgs> | null
  /**
   * Omit specific fields from the session_tokens
   */
  omit?: Prisma.session_tokensOmit<ExtArgs> | null
  /**
   * The data needed to create a session_tokens.
   */
  data: Prisma.XOR<Prisma.session_tokensCreateInput, Prisma.session_tokensUncheckedCreateInput>
}

/**
 * session_tokens createMany
 */
export type session_tokensCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many session_tokens.
   */
  data: Prisma.session_tokensCreateManyInput | Prisma.session_tokensCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * session_tokens update
 */
export type session_tokensUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the session_tokens
   */
  select?: Prisma.session_tokensSelect<ExtArgs> | null
  /**
   * Omit specific fields from the session_tokens
   */
  omit?: Prisma.session_tokensOmit<ExtArgs> | null
  /**
   * The data needed to update a session_tokens.
   */
  data: Prisma.XOR<Prisma.session_tokensUpdateInput, Prisma.session_tokensUncheckedUpdateInput>
  /**
   * Choose, which session_tokens to update.
   */
  where: Prisma.session_tokensWhereUniqueInput
}

/**
 * session_tokens updateMany
 */
export type session_tokensUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update session_tokens.
   */
  data: Prisma.XOR<Prisma.session_tokensUpdateManyMutationInput, Prisma.session_tokensUncheckedUpdateManyInput>
  /**
   * Filter which session_tokens to update
   */
  where?: Prisma.session_tokensWhereInput
  /**
   * Limit how many session_tokens to update.
   */
  limit?: number
}

/**
 * session_tokens upsert
 */
export type session_tokensUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the session_tokens
   */
  select?: Prisma.session_tokensSelect<ExtArgs> | null
  /**
   * Omit specific fields from the session_tokens
   */
  omit?: Prisma.session_tokensOmit<ExtArgs> | null
  /**
   * The filter to search for the session_tokens to update in case it exists.
   */
  where: Prisma.session_tokensWhereUniqueInput
  /**
   * In case the session_tokens found by the `where` argument doesn't exist, create a new session_tokens with this data.
   */
  create: Prisma.XOR<Prisma.session_tokensCreateInput, Prisma.session_tokensUncheckedCreateInput>
  /**
   * In case the session_tokens was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.session_tokensUpdateInput, Prisma.session_tokensUncheckedUpdateInput>
}

/**
 * session_tokens delete
 */
export type session_tokensDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the session_tokens
   */
  select?: Prisma.session_tokensSelect<ExtArgs> | null
  /**
   * Omit specific fields from the session_tokens
   */
  omit?: Prisma.session_tokensOmit<ExtArgs> | null
  /**
   * Filter which session_tokens to delete.
   */
  where: Prisma.session_tokensWhereUniqueInput
}

/**
 * session_tokens deleteMany
 */
export type session_tokensDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which session_tokens to delete
   */
  where?: Prisma.session_tokensWhereInput
  /**
   * Limit how many session_tokens to delete.
   */
  limit?: number
}

/**
 * session_tokens without action
 */
export type session_tokensDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the session_tokens
   */
  select?: Prisma.session_tokensSelect<ExtArgs> | null
  /**
   * Omit specific fields from the session_tokens
   */
  omit?: Prisma.session_tokensOmit<ExtArgs> | null
}
